// data.js — Collection and Wishlist
// Format: [artist, title, year, value, genre]
const COLL = [
  ["The Police","Synchronicity","1983",12,"Rock / New Wave"],
  ["The Floaters","The Floaters","1977",6,"Soul / Funk"],
  ["Little Simz","Grey Area","2019",18,"Hip-Hop"],
  ["The Three Degrees","New Dimensions","1978",6,"Soul / Funk"],
  ["The Three Degrees","The Three Degrees","1973",8,"Soul / Funk"],
  ["Whitney Houston","Whitney Houston","1985",8,"R&B / Pop"],
  ["Whitney Houston","Whitney","1987",8,"R&B / Pop"],
  ["Wilson Pickett","The Best of Wilson Pickett","1984",6,"Soul / Funk"],
  ["Joe Tex","The Best of Joe Tex","1984",5,"Soul / Funk"],
  ["Sam & Dave","The Best of Sam & Dave","1984",6,"Soul / Funk"],
  ["Boney M.","Nightflight to Venus","1978",8,"Disco / Pop"],
  ["The Stylistics","Stylistics 2","1972",10,"Soul / Funk"],
  ["The Stylistics","Thank You Baby","1975",8,"Soul / Funk"],
  ["The Stylistics","You Are Beautiful","1975",8,"Soul / Funk"],
  ["Flohio","Out of Heart","2022",15,"Hip-Hop"],
  ["Tina Turner","Private Dancer","1984",8,"R&B / Pop"],
  ["Diana Ross","Why Do Fools Fall in Love","1981",8,"Motown"],
  ["Diana Ross","Eaten Alive","1985",6,"Motown"],
  ["Donna Summer","Bad Girls","1979",12,"Disco / Pop"],
  ["Marvin Gaye","Midnight Love","1982",10,"Motown"],
  ["Cheryl Lynn","In Love","1979",8,"Soul / Funk"],
  ["Deniece Williams","Song Bird","1977",10,"Soul / Funk"],
  ["Deniece Williams","This Is Niecy","1976",10,"Soul / Funk"],
  ["Earth, Wind & Fire","The Best of Earth Wind & Fire Vol. I","1978",10,"Soul / Funk"],
  ["Earth, Wind & Fire","I Am","1979",12,"Soul / Funk"],
  ["The Clash","Combat Rock","1982",12,"Rock / New Wave"],
  ["Labi Siffre","Something Inside So Strong","1987",15,"Soul / Funk"],
  ["Fugees","The Score","1996",20,"Hip-Hop"],
  ["Koffee","Rapture","2019",15,"Reggae"],
  ["Tyler, The Creator","Scum Fuck Flower Boy","2017",20,"Hip-Hop"],
  ["Nas","Illmatic","1994",20,"Hip-Hop"],
  ["Tyler, The Creator","Igor","2019",22,"Hip-Hop"],
  ["Sister Sledge","We Are Family","1979",12,"Soul / Funk"],
  ["Khruangbin","Mordechai","2020",18,"Neo-Soul / Leftfield"],
  ["Various Artists","Def Jamaica Sampler","2003",8,"Reggae"],
  ["Jaki Graham","Breaking Away","1986",6,"R&B / Pop"],
  ["Michael Jackson","Off the Wall","1979",15,"Soul / Funk"],
  ["Michael Jackson","Thriller","1982",18,"R&B / Pop"],
  ["Minnie Riperton","Perfect Angel","1974",20,"Soul / Funk"],
  ["Sade","Diamond Life","1984",15,"Neo-Soul / Leftfield"],
  ["Sade","Promise","1985",25,"Neo-Soul / Leftfield"],
  ["Jorja Smith","Be Right Back","2021",18,"Neo-Soul / Leftfield"],
  ["Seratones","Get Gone","2016",12,"Rock / New Wave"],
  ["Queen Latifah","All Hail the Queen","1989",15,"Hip-Hop"],
  ["Rick James","Cold Blooded","1983",10,"Soul / Funk"],
  ["The Stylistics","Fabulous","1976",8,"Soul / Funk"],
  ["Kendrick Lamar","Good Kid M.A.A.D City","2012",25,"Hip-Hop"],
  ["Bob Marley & The Wailers","Kaya","1978",12,"Reggae"],
  ["Bob Marley & The Wailers","Catch a Fire","1973",15,"Reggae"],
  ["Bob Marley & The Wailers","Exodus","1977",15,"Reggae"],
  ["Angel Olsen","All Mirrors","2019",15,"Neo-Soul / Leftfield"],
  ["Electric Light Orchestra","Out of the Blue","1977",12,"Rock / New Wave"],
  ["Louis Armstrong","The New Orleans Function","1950",8,"Jazz"],
  ["Fleetwood Mac","Greatest Hits","1988",10,"Rock / New Wave"],
  ["The KLF","Justified & Ancient","1991",12,"Electronic"],
  ["Sampa The Great","As Above So Below","2022",18,"Hip-Hop"],
  ["The Communards","Red","1987",10,"Electronic"],
  ["The Communards","Communards","1986",10,"Electronic"],
  ["Neil Diamond","20 Golden Greats","1978",5,"Rock / New Wave"],
  ["10cc","The Original Soundtrack","1975",10,"Rock / New Wave"],
  ["Dexys Midnight Runners","Too-Rye-Ay","1982",12,"Rock / New Wave"],
  ["Rococo","Italo House Mix","1989",8,"Electronic"],
  ["Stevie Wonder","Hotter Than July","1981",12,"Motown"],
  ["Lionel Richie","Dancing on the Ceiling","1986",8,"R&B / Pop"],
  ["Diana Ross","Baby It's Me","1977",8,"Motown"],
  ["Lionel Richie","Lionel Richie","1982",8,"R&B / Pop"],
  ["Commodores","Midnight Magic","1979",10,"Soul / Funk"],
  ["Commodores","Greatest Hits","1978",10,"Soul / Funk"],
  ["Diana Ross","The Boss","1979",10,"Motown"],
  ["Lionel Richie","Can't Slow Down","1983",8,"R&B / Pop"],
  ["The Supremes","Baby Love","1964",8,"Motown"],
  ["Seratones","Power","2019",12,"Rock / New Wave"],
  ["The Jam","This Is the Modern World","1977",15,"Rock / New Wave"],
  ["Sweet Sensation","Sad Sweet Dreamer","1974",8,"Soul / Funk"],
  ["Eurythmics","Be Yourself Tonight","1985",8,"Rock / New Wave"],
  ["Eurythmics","Revenge","1986",8,"Rock / New Wave"],
  ["Mustafa","When Smoke Rises","2021",18,"Neo-Soul / Leftfield"],
  ["Solange","A Seat at the Table","2016",20,"Neo-Soul / Leftfield"],
  ["Shalamar","Friends","1982",10,"Soul / Funk"],
  ["Various Artists","Doing It in Lagos","2016",20,"Soul / Funk"],
  ["Various Artists","Rap Trax","1988",10,"Hip-Hop"],
  ["Marvin Gaye","What's Going On","1971",20,"Motown"],
  ["Stevie Wonder","Talking Book","1972",15,"Motown"],
  ["Stevie Wonder","Songs in the Key of Life","1976",35,"Motown"],
  ["Diana Ross & Marvin Gaye","Diana & Marvin","1973",15,"Motown"],
  ["The Supremes & Four Tops","The Magnificent 7","1971",12,"Motown"],
  ["Diana Ross","I'm Still Waiting","1971",10,"Motown"],
  ["Gladys Knight & The Pips","Help Me Make It Through the Night","1972",8,"Motown"],
  ["Diana Ross","Touch Me in the Morning","1973",10,"Motown"],
  ["Michael Jackson","Love Songs","1987",8,"R&B / Pop"],
  ["Bina.","Chaos is her name","2024",15,"Neo-Soul / Leftfield"],
  ["SZA","Ctrl","2017",20,"Neo-Soul / Leftfield"],
  ["The Gap Band","Gap Band IV","1982",12,"Soul / Funk"],
  ["Genesis","Invisible Touch","1986",8,"Rock / New Wave"],
  ["Neneh Cherry","Homebrew","1992",18,"Neo-Soul / Leftfield"],
  ["Culture Club","Kissing to Be Clever","1982",10,"Rock / New Wave"],
  ["George Benson","The George Benson Collection","1981",8,"Jazz"],
  ["Labi Siffre","Remember My Song","1975",15,"Soul / Funk"],
  ["Rose Royce","In Full Bloom","1977",10,"Soul / Funk"],
  ["Rose Royce","Strikes Again","1978",8,"Soul / Funk"],
  ["Rose Royce","Rose Royce Greatest Hits","1980",8,"Soul / Funk"],
  ["New Gen","New Gen","2017",12,"Hip-Hop"],
  ["Chic","Chic","1977",11,"Soul / Funk"],
  ["Amy Winehouse","Back to Black","2006",20,"Soul / Funk"],
  ["David Bowie","Changes One Bowie","1976",15,"Rock / New Wave"],
  ["David Bowie","Changes Two Bowie","1981",12,"Rock / New Wave"],
  ["T. Rex","The Slider","1972",15,"Rock / New Wave"],
  ["Kendrick Lamar","To Pimp a Butterfly","2015",28,"Hip-Hop"],
  ["Jorja Smith","Lost & Found","2018",18,"Neo-Soul / Leftfield"],
  ["M.E.B.","That You Not Dare to Forget","2023",25,"Jazz"],
  ["Jorja Smith","Falling or Flying","2023",20,"Neo-Soul / Leftfield"],
];

// [artist, title, year, price, tier, spotify, genre, hmvNote]
const WISH = [
  ["Al Green","Let's Stay Together","1972",12,"sh",false,"Soul / Funk","nothmv"],
  ["Marvin Gaye","Let's Get It On","1973",12,"sh",false,"Motown","nothmv"],
  ["Curtis Mayfield","Superfly","1972",12,"sh",false,"Soul / Funk","nothmv"],
  ["A Tribe Called Quest","The Low End Theory","1991",22,"hmv",false,"Hip-Hop","deal"],
  ["Lauryn Hill","The Miseducation of Lauryn Hill","1998",22,"hmv",false,"Hip-Hop","deal"],
  ["De La Soul","3 Feet High and Rising","1989",25,"hmv",false,"Hip-Hop","deal"],
  ["Funkadelic","Maggot Brain","1971",22,"store",false,"Soul / Funk","nothmv"],
  ["Frank Ocean","Channel Orange","2012",30,"patience",false,"Neo-Soul / Leftfield","nothmv"],
  ["Curtis Mayfield","Curtis","1970",22,"store",false,"Soul / Funk","nothmv"],
  ["J Dilla","Donuts","2006",25,"store",false,"Hip-Hop","nothmv"],
  ["KAYTRANADA","99.9%","2016",22,"hmv",true,"Electronic","deal"],
  ["Mac Miller","Swimming","2018",25,"store",true,"Hip-Hop","nothmv"],
  ["Thundercat","Drunk","2017",22,"store",true,"Neo-Soul / Leftfield","nothmv"],
  ["The Internet","Ego Death","2015",22,"store",true,"Neo-Soul / Leftfield","nothmv"],
  ["Snoh Aalegra","Feels","2018",20,"store",true,"Neo-Soul / Leftfield","nothmv"],
  ["Kali Uchis","Isolation","2018",20,"store",true,"Neo-Soul / Leftfield","nothmv"],
  ["Joey Bada$$","All-Amerikkkan Bada$$","2017",20,"store",true,"Hip-Hop","nothmv"],
  ["Isley Brothers","3+3","1973",12,"sh",false,"Soul / Funk","nothmv"],
  ["Sly & The Family Stone","There's a Riot Goin' On","1971",12,"sh",false,"Soul / Funk","nothmv"],
  ["Barry White","Can't Get Enough","1974",8,"sh",false,"Soul / Funk","nothmv"],
  ["Rufus & Chaka Khan","Rufusized","1974",10,"sh",false,"Soul / Funk","nothmv"],
  ["Gladys Knight & The Pips","Imagination","1973",8,"sh",false,"Motown","nothmv"],
  ["Bobby Womack","The Poet","1981",10,"sh",false,"Soul / Funk","nothmv"],
  ["Roy Ayers","Everybody Loves the Sunshine","1976",28,"patience",false,"Jazz","nothmv"],
  ["Minnie Riperton","Adventures in Paradise","1975",15,"sh",false,"Soul / Funk","nothmv"],
  ["Tom Misch","Geography","2018",18,"store",false,"Neo-Soul / Leftfield","nothmv"],
  ["Little Simz","Sometimes I Might Be Introvert","2021",22,"store",false,"Hip-Hop","deal"],
  ["Little Simz","No Thank You","2022",22,"store",false,"Hip-Hop","deal"],
  ["J Hus","Big Conspiracy","2020",22,"store",false,"Hip-Hop","deal"],
  ["Barry Can't Swim","When Will We Land?","2023",22,"store",false,"Electronic","deal"],
  ["Doechii","Alligator Bites Never Heal","2024",27,"store",false,"Hip-Hop","nothmv"],
  ["Knucks","Alpha Place","2022",22,"store",false,"Hip-Hop","deal"],
  ["Otis Redding","The Best of Otis Redding","1972",8,"sh",false,"Soul / Funk","nothmv"],
  ["Aretha Franklin","I Never Loved a Man the Way I Love You","1967",8,"sh",false,"Soul / Funk","nothmv"],
  ["Booker T & The MGs","Green Onions","1962",8,"sh",false,"Soul / Funk","nothmv"],
  ["David Gray","White Ladder","1998",28,"store",false,"Rock / New Wave","deal"],
  ["Kamasi Washington","The Epic","2015",45,"patience",false,"Jazz","nothmv"],
  ["The Beach Boys","Pet Sounds","1966",22,"store",false,"Rock / New Wave","deal"],
  ["Labi Siffre","Crying Laughing Loving Lying","1971",20,"store",false,"Soul / Funk","nothmv"],
  ["LCD Soundsystem","Sound of Silver","2007",28,"store",false,"Electronic","nothmv"],
  ["Arctic Monkeys","Favourite Worst Nightmare","2007",22,"store",false,"Rock / New Wave","deal"],
  ["Tame Impala","Currents","2015",28,"store",false,"Neo-Soul / Leftfield","deal"],
  ["The Roots","Things Fall Apart","1999",35,"patience",false,"Hip-Hop","nothmv"],
  ["Nujabes","Modal Soul","2005",35,"patience",false,"Jazz","nothmv"],
  ["Pulp","Different Class","1995",25,"store",false,"Rock / New Wave","deal"],
  ["OutKast","Aquemini","1998",35,"patience",false,"Hip-Hop","nothmv"],
  ["OutKast","ATLiens","1996",45,"patience",false,"Hip-Hop","nothmv"],
  ["Erykah Badu","Baduizm","1997",28,"store",false,"Neo-Soul / Leftfield","nothmv"],
  ["MGMT","Oracular Spectacular","2007",22,"store",false,"Rock / New Wave","deal"],
  ["Erykah Badu","Mama's Gun","2000",28,"store",false,"Neo-Soul / Leftfield","nothmv"],
  ["Hiroshi Suzuki","Cat","1976",35,"patience",false,"Jazz","nothmv"],
  ["David Bowie","The Rise and Fall of Ziggy Stardust","1972",25,"store",false,"Rock / New Wave","deal"],
  ["Talking Heads","Speaking in Tongues","1983",28,"store",false,"Rock / New Wave","deal"],
  ["Kanye West","My Beautiful Dark Twisted Fantasy","2010",40,"patience",false,"Hip-Hop","nothmv"],
  ["D'Angelo","Voodoo","2000",28,"store",false,"Neo-Soul / Leftfield","nothmv"],
  ["Massive Attack","Blue Lines","1991",22,"store",false,"Electronic","deal"],
  ["Fontaines D.C.","Romance","2024",25,"store",false,"Rock / New Wave","deal"],
];
